In [13]:
# Exercício 1: Produto Escalar em Aplicação Prática
# Descrição:  Dados  dois  vetores  que  representam  preferências  de  usuários  em  três categorias diferentes 
# user1 = [4, 3, 2] e user2 = [1, 5, 4], calcule a similaridade entre esses usuários usando o produto escalar.

# Importando a biblioteca Python
import numpy as np

# Definindo os vetores
user1 = np.array([4, 3, 2])
user2 = np.array([1, 5, 4])

# Calcular o produto escalar (dot product)
resultado_1 = np.dot( user1, user2 )
print(resultado_1)

27


In [14]:
# Explicação: O número resultante da operação significa a magnitude da similaridade onde, quanto maior for o número maior será a similaridade entre eles. 
# Sendo positivo significa que os vetores apontam na mesma direção tenho uma orientação geral semelhante no espaço vetorial considerado.
# Indica portanto na questão de contexto destes dados que os mesmos possuem alta similaridade de preferências.

In [20]:
# Exercício 2: Multiplicação de Escalar por Vetor em Dados Reais
# Descrição: Dada uma série de preços de ações prices= [120, 125, 130, 128, 135], ajuste os preços em 15% e calcule o novo preço das ações.

# Importando a biblioteca Python
import numpy as np

# Definindo o vetor
prices = np.array([120, 125, 130, 128, 135])

#Definindo o valor escalar
ajuste = 0.15

# Calculando a multiplicação escalar
resultado_2a = prices * ajuste
print(resultado_2a)

# Calculando o novo valor dos preços
resultado_2b = resultado_2a + prices
print(resultado_2b)


[18.   18.75 19.5  19.2  20.25]
[138.   143.75 149.5  147.2  155.25]


In [21]:
# Opção 2 - Exercício 2

# Importando a biblioteca Python
import numpy as np

# Definindo o vetor
prices = np.array([120, 125, 130, 128, 135])

#Definindo o valor escalar
ajuste = 1.15

# Calculando a multiplicação escalar e o ajuste nos preços
resultado_2c = prices * ajuste
print(resultado_2c)

[138.   143.75 149.5  147.2  155.25]


In [34]:
# Exercício 3: Otimização de Produto Escalar
# Descrição: Encontre o vetor unitário que maximiza o produto escalar com o vetor v = [3, 4, 5]. 
# Use técnicas de otimização para encontrar a solução.

# Importando a biblioteca Python
import numpy as np
import scipy
from scipy.optimize import minimize # função geral para otimização numérica de funções escalares.

# Definindo o vetor
v = np.array([3, 4, 5])

# Função objetivo para calcular o produto escalar negativo do vetor v com o vetor x. 
def funcao_objetivo(x):
    return -np.dot(v, x)

# Variável constraint como restrição para exigir que a magnitude do vetor x seja 1, tornando o vetor unitário.
constraint = { 'type': 'eq', 'fun': lambda x: np.linalg.norm(x) -1 }
# Chave 'type': 'eq' indica a restrição de igualdade devendo a função resultar em 0

# Solução para a otimização
resultado_3 = minimize(funcao_objetivo, np.ones(3), constraints = constraint)
vetor_otimizado = resultado_3.x

print(vetor_otimizado)


[0.42427197 0.56568183 0.70710492]
